version: "3.4"
services:
  autobot-development:
    container_name: autobot-development
    build:
      context: ./docker
      dockerfile: Dockerfile
      target: development
      args:
        org_name: ucfai
        env_name: autobot  # setup to work dynamically from conda env
    volumes:
      - .:/autobot
      - ./docker/groups/:/ucfai/
      - ./docker/ucfai.org/:/ucfai.org/
      # - ./docker/conda:/opt/conda/envs/autobot

  # autobot-production:
  #   container_name: autobot-production
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: production

  hugo:
    image: jojomi/hugo:0.60.0
    container_name: autobot-hugo
    environment:
      - HUGO_THEME=academic
      - HUGO_WATCH=true
      # - HUGO_BASEURL=
    volumes:
      - ./docker/ucfai.org:/src
      # use the volume mount below to inspect the hugo output, IFF needed
      # - ./build:/output
    ports:
      - 8234:1313
