version: "3.4"
services:
  autobot-development:
    container_name: autobot-development
    build:
      context: ./docker/container.autobot
      dockerfile: Dockerfile
      target: development
      args:
        org_name: ucfai
        env_name: autobot  # setup to work dynamically from conda env
    volumes:
      - .:/autobot
      - ./docker/volume.groups/:/ucfai/
      - ./docker/volume.ucfai.org/:/ucfai.org/
      - ./docker/container.autobot:/docker

  # autobot-production:
  #   container_name: autobot-production
  #   build:
  #     context: ./docker/container.autobot
  #     dockerfile: autobot.Dockerfile
  #     target: production

  autobot-hugo:
    image: jojomi/hugo:0.60.0
    container_name: autobot-hugo
    environment:
      - HUGO_THEME=academic
      - HUGO_WATCH=true
      # - HUGO_BASEURL=
    volumes:
      - ./docker/volume.ucfai.org:/src
      # use the volume mount below to inspect the hugo output, IFF needed
      # - ./build:/output
    ports:
      - 8234:1313

  # TODO this currently works *_only_* on a Linux host, b/c of `evdev`. Figure out if
  #      there's a way to get around that limitation.
  # autobot-reader:
  #   container_name: autobot-reader
  #   build:
  #     context: ./docker/container.reader
  #     dockerfile: Dockerfile
  #   volumes:
  #     - .:/autobot
  #     - ./docker/container.reader:/docker
  #     - ./docker/volume.reader:/reader