name: "Rebuild development/production containers"
author: "<@ionlights> John Muchovej"
description: >-
  Development containers are basically for local development and testing, while
  production is for usage when doing validation across each of AI@UCF's groups.

on:
  push:
    branches:
      - master
    paths:
      - "autobot"
      - "docker/container.autobot"
  pull_request:
    branches:
      - master
    paths:
      - "autobot"
      - "docker/container.autobot"

jobs:
  build-development:
    needs: build-env

    runs-on: ubuntu-latest

    env:
      STAGE: development
      TARGET: development
      ORG_NAME: ucfai
      ENV_NAME: autobot
      REPO_NAME: bot
      REGISTRY: "docker.pkg.github.com"

    steps:
    - name: "Checkout Latest `master` branch"
      uses: actions/checkout@v2

    - name: "Set variables to make this semi-dynamic"
      run: |
        echo "${STAGE}-$(date +%s)" > VERSION
        DOCKER_TAG="${REGISTRY}/${ORG_NAME}/${REPO_NAME}/${STAGE}"
        echo "${DOCKER_TAG}:$(cat VERSION)" > TAG_VERSION
        echo "${DOCKER_TAG}:latest" > TAG_LATEST

    - name: "Build the container"
      run: |
        docker build docker/container.autobot \
          --target ${TARGET} \
          --build-arg org_name=${ORG_NAME} \
          --build-arg env_name=${ENV_NAME} \
          --tag $(cat TAG_VERSION) \
          --tag $(cat TAG_LATEST)

    - name: "Push the container to ${REGISTRY}"
      run: |
        docker login ${REGISTRY} --username ${ORG_NAME} --password ${{ secrets.GITHUB_TOKEN }}
        docker push $(cat TAG_VERSION)
        docker push $(cat TAG_LATEST)

  build-production:
    needs: build-env

    runs-on: ubuntu-latest

    env:
      STAGE: production
      TARGET: production
      ORG_NAME: ucfai
      ENV_NAME: autobot
      REPO_NAME: bot
      REGISTRY: "docker.pkg.github.com"

    steps:
    - name: "Checkout Latest `master` branch"
      uses: actions/checkout@v2

    - name: "Set variables to make this semi-dynamic"
      run: |
        echo "${STAGE}-$(date +%s)" > VERSION
        DOCKER_TAG="${REGISTRY}/${ORG_NAME}/${REPO_NAME}/${STAGE}"
        echo "${DOCKER_TAG}:$(cat VERSION)" > TAG_VERSION
        echo "${DOCKER_TAG}:latest" > TAG_LATEST

    - name: "Build the container"
      run: |
        docker build docker/container.autobot \
          --target ${TARGET} \
          --build-arg org_name=${ORG_NAME} \
          --build-arg env_name=${ENV_NAME} \
          --tag $(cat TAG_VERSION) \
          --tag $(cat TAG_LATEST)

    - name: "Push the container to ${REGISTRY}"
      run: |
        docker login ${REGISTRY} --username ${ORG_NAME} --password ${{ secrets.GITHUB_TOKEN }}
        docker push $(cat TAG_VERSION)
        docker push $(cat TAG_LATEST)