name: "Build Docker image for autobot"

on:
  push:
    paths:
      - ".github/workflows/docker.yml"
      - "src/*"
      - "tests/*"
      - "entrypoint.sh"
      - "Dockerfile"
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      - "src/*"
      - "tests/*"
      - "entrypoint.sh"
      - "Dockerfile"

env:
  REGISTRY: docker.pkg.github.com

jobs:
  build:
    name: Build Docker Container

    runs-on: ubuntu-latest

    steps:
    - name: Checkout tasks repository
      uses: actions/checkout@v2

    - name: Get release version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF/refs\/tags\//})

    - name: Build Dockerfile
      uses: elgohr/Publish-Docker-Github-Action@2.16
      with:
        name: ionlights/autobot
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PAT }}
        # registry: ${{ env.REGISTRY }}
        tags: latest