name: "Rebuild containers that allow for a portable `autobot`."

# TODO migrate repeated steps to a GitHub action

on:
  push:
    paths:
      - ".github/workflows/"
      - "autobot/"
      - "docker/container.autobot/"
  pull_request:
    paths:
      - ".github/workflows/"
      - "autobot/"
      - "docker/container.autobot/"

jobs:
  build-env:
    runs-on: ubuntu-latest

    env:
      STAGE: env
      TARGET: autobotbase
      ORG_NAME: ucfai
      ENV_NAME: autobot
      REPO_NAME: bot
      REGISTRY: "docker.pkg.github.com"

    steps:
    - name: "Checkout latest `master` branch"
      uses: actions/checkout@v2

    - name: "Set variables to make this semi-dynamic"
      run: |
        echo "${STAGE}-$(date +%s)" > VERSION
        DOCKER_TAG="${REGISTRY}/${ORG_NAME}/${REPO_NAME}/${STAGE}"
        echo "${DOCKER_TAG}:$(cat VERSION)" > TAG_VERSION
        echo "${DOCKER_TAG}:latest" > TAG_LATEST

    - name: "Build the container"
      run: |
        docker build docker/container.autobot \
          --target ${TARGET} \
          --build-arg org_name=${ORG_NAME} \
          --build-arg env_name=${ENV_NAME} \
          --tag $(cat TAG_VERSION) \
          --tag $(cat TAG_LATEST)

    - name: "Push the container to ${REGISTRY}"
      run: |
        docker login ${REGISTRY} --username ${ORG_NAME} --password ${{ secrets.GITHUB_TOKEN }}
        docker push $(cat TAG_VERSION)
        docker push $(cat TAG_LATEST)

  build-development:
    needs: build-env

    runs-on: ubuntu-latest

    env:
      STAGE: development
      TARGET: development
      ORG_NAME: ucfai
      ENV_NAME: autobot
      REPO_NAME: bot
      REGISTRY: "docker.pkg.github.com"

    steps:
    - name: "Checkout Latest `master` branch"
      uses: actions/checkout@v2

    - name: "Set variables to make this semi-dynamic"
      run: |
        echo "${STAGE}-$(date +%s)" > VERSION
        DOCKER_TAG="${REGISTRY}/${ORG_NAME}/${REPO_NAME}/${STAGE}"
        echo "${DOCKER_TAG}:$(cat VERSION)" > TAG_VERSION
        echo "${DOCKER_TAG}:latest" > TAG_LATEST

    - name: "Build the container"
      run: |
        docker build docker/container.autobot \
          --target ${TARGET} \
          --build-arg org_name=${ORG_NAME} \
          --build-arg env_name=${ENV_NAME} \
          --tag $(cat TAG_VERSION) \
          --tag $(cat TAG_LATEST)

    - name: "Push the container to ${REGISTRY}"
      run: |
        docker login ${REGISTRY} --username ${ORG_NAME} --password ${{ secrets.GITHUB_TOKEN }}
        docker push $(cat TAG_VERSION)
        docker push $(cat TAG_LATEST)

  build-production:
    needs: build-env

    runs-on: ubuntu-latest

    env:
      STAGE: production
      TARGET: production
      ORG_NAME: ucfai
      ENV_NAME: autobot
      REPO_NAME: bot
      REGISTRY: "docker.pkg.github.com"

    steps:
    - name: "Checkout Latest `master` branch"
      uses: actions/checkout@v2

    - name: "Set variables to make this semi-dynamic"
      run: |
        echo "${STAGE}-$(date +%s)" > VERSION
        DOCKER_TAG="${REGISTRY}/${ORG_NAME}/${REPO_NAME}/${STAGE}"
        echo "${DOCKER_TAG}:$(cat VERSION)" > TAG_VERSION
        echo "${DOCKER_TAG}:latest" > TAG_LATEST

    - name: "Build the container"
      run: |
        docker build docker/container.autobot \
          --target ${TARGET} \
          --build-arg org_name=${ORG_NAME} \
          --build-arg env_name=${ENV_NAME} \
          --tag $(cat TAG_VERSION) \
          --tag $(cat TAG_LATEST)

    - name: "Push the container to ${REGISTRY}"
      run: |
        docker login ${REGISTRY} --username ${ORG_NAME} --password ${{ secrets.GITHUB_TOKEN }}
        docker push $(cat TAG_VERSION)
        docker push $(cat TAG_LATEST)
